name: Run test.bat locally

on:
  workflow_dispatch:

jobs:
  run-local:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Execute test.bat
        run: |
          echo "Running test.bat..."
          cd ${{ github.workspace }}
          echo "SECRET_ID (from pipeline): $env:SECRET_ID"
          .\test.bat
        shell: pwsh
        env:
          SECRET_ID: ${{ secrets.SECRET_ID }}
